import { UniversityInfo, Department, SearchItem } from "./types";

export const UNIVERSITIES: Record<string, UniversityInfo> = {
  cbnu: {
    id: "cbnu",
    nameKo: "충북대학교",
    nameEn: "Chungbuk National University",
    logoUrl: "https://lh3.googleusercontent.com/aida/ADBb0uga4WZMyOut4GqsHAb-1wJIdB8DROz9tDs6PuU7tf8q7M39VVDEwEZK9ECpQEknaczhnikPce_DPo5gV-ZDAIcGdNBcpTKuCK1aqBg8xUdoj4RjLPrVq071vTmom_GRJRqkwP6gcVIj9QM7qJDtt8MDqwOyFXM10dwlEqwqQLUzjnU4Yz64ac49hiJrw5cg073d4iXyh5Dx6z3papLhjAkiH4iSTDtrLtUmsPEfRTnFzRzIkKmgCdyW24Q",
    heroUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCKchM5IvaitLpXAkaLlifEHghtK0C6BDO_HGTolRaagepAhdBUxgqD01WrE8sx-IZxM5R6uvadmvtUGilLmJBnw29thHSRYFHHIow25dV2XbWU6PTWp-oO7n6uEWZcXxVcRjxPeo-POLkvbMfGF_r2SwOrDE0UTaakmislfii2ypmR01OiSfmoqr5auoZRa0Bl-mHeAx_MtfO_bLC933fkuT3EjsYtDiGmOuAPQaFufhR9pvWNHkgy0jfvmkyytPnwaaDGw7nbSYQ",
    brandColor: "#052e16", // CBNU typical deep forest-looking signature, or deep blue
    accentColor: "#1d4ed8", // Slate Blue Accent
    textColor: "#111827",
    foundingYear: 1951,
    stats: {
      students: "24,500+",
      professors: "850+",
      employmentRate: "68.4%",
      globalRank: "Ranked 10th among National Universities in Korea",
    },
    addressKo: "충청북도 청주시 서원구 충대로 1",
    addressEn: "1 Chungdae-ro, Seowon-gu, Cheongju, Chungcheongbuk-do, Korea",
    tel: "043-261-2114",
    email: "admissions@cbnu.ac.kr",
  },
  cju: {
    id: "cju",
    nameKo: "청주대학교",
    nameEn: "Cheongju University",
    logoUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAbMyIG8nOM-tecARpZwzHbOooHz-cMZaLkKv3Tou22xk3gvMwbKdSfjvEVlFhBJ-WGhl55bsEVUGXMq3CVpy8p2wNcezitRV3IYd9uAe-fb4eKsridhaOEeByK9VvSGPFCgXCwZyy1j5fSfLy5sZQrfOvXLkrTWQu0PF9oDH8WL6-KZQj2p-44oQBTxFYBOPc-SMIGkbsdQLyDZHrozWSdLud3WrF6sSlL3t2nDgV4zwZwzHYxKj6YhsXYq248iwMe_6XFGU1WX3M",
    logoTextUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBWNag9UHqKkzdtIcI5LhkvKmfXHska-Pk13dagiJ_Rx0JjZUcUBOx5coKyjjE708jecBUYFVvPOhPqk_1YZ6eX6xDqXnuLn6pvLfDshKTKI3j04QeF1ymkXTM7OiCNiwzZnWZA-Wy8CXvqdmemPGX4OdTsTSII66quzGK-VIjrZJ6wUS2d4MQg8OsOHVvr32rD047lzM7EjF_lt12qwnsqsiudSRDZGP63TaCCHrwT4FTTFLN_sJKeuyGPCbIYsX-5Ba06f8hQ3BQ",
    heroUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDfBM9U5ZphoV1AfmEZpVmiioTKBZ8HOaiMLCE706Khb1BVBblRLpeXJ3QwCBQbKrglHue9NcPT_gzPeSslVS0bn0PKtcPh-zFLCgpWRCVXZ4g9Rh4V-pxKbNVIcOd8zpGsE5idy1ALLaycI0pQB2GCZorWIFq-tG5Sju61SA-DJkN6WYsS3SWDMPhsbV2KdP18RrmHoJz_U0yAKQvWVSXs4Rw9jc-pQAGx4u-kF5v_7RyCgtSWZaianzP8ilt4Cb6o3vE8c0L9wPE",
    brandColor: "#0f5132", // Forest Green primary brand representation as seen in Image 6
    accentColor: "#ea580c", // Energetic orange accent or emerald highlights
    textColor: "#1f2937",
    foundingYear: 1947,
    stats: {
      students: "15,800+",
      professors: "520+",
      employmentRate: "65.8%",
      globalRank: "Top-Tier Private University in Central region",
    },
    addressKo: "충청북도 청주시 청원구 대성로 298",
    addressEn: "298 Daeseong-ro, Cheongwon-gu, Cheongju, Chungcheongbuk-do, Korea",
    tel: "043-229-8114",
    email: "enter@cju.ac.kr",
  },
};

export const HOTLINKS = {
  campusMain: "https://lh3.googleusercontent.com/aida-public/AB6AXuBUvpL4xkTiK9cGPQ4EU5TUrz6iE4IAeOgavXBTjHIB4XSHJIlK5g9k7HsAS4T6Ii-3x7ccdCXvHCn7BbIVP6MdInTz-y4qwz_LCmuP3qmPVA5wDnAyz3EIVgfiTeZDvRmTMwV1hmvkp-fkUR5kZuUEx8Xu5JoCtAmdxgumen929DBic3sXwZL538uvpDX4csvs3Cze9i90k2fhzW3SsG5cFHv9iMS5GGNKpVY81vR-NzbsyWx8Rl2PIfW_WG61ZscrtQAU0Q17fGo",
  campusBuilding: "https://lh3.googleusercontent.com/aida-public/AB6AXuDtxcUV7Tw3o0Bh4zZrRCN-FH_tQTi5uKUxfClI5e4dgb-GbTPXF3pkIc6QPHM1wrg-pYbSuHM_p2spM-OivxJ2W4FDCS9CMu39YNOUoGV6lMhBZr2bX78QQRFiPc6YcQFqupJcSmtHWdy4BtJMhI1SXKtflWoe18U6d-S1QlsxA2zIMIbm8fjN9N5ZmHeVJfipz-7cf84WkMkedciCd4rLli2Y7oU6rfInEXxDVaOgGfSXXXt6RkcXdjVD6fKqbtcp4zEA2ROTuP8",
};

export const DEPARTMENTS: Department[] = [
  {
    id: "dept-1",
    category: "engineering",
    nameKo: "컴퓨터공학과",
    nameEn: "Computer Science & Engineering",
    descKo: "최고의 교수진과 실무 중심 교육을 통해 AI, 클라우드, 소프트웨어 전문가를 양성합니다.",
    descEn: "Nurturing AI, Cloud, and Software experts with world-class faculty and hands-on industry collaboration.",
    featuresKo: ["인공지능 트랙 특성화", "산학 융합 캡스톤 디자인 코스", "해외 대학 연계 인턴십"],
    featuresEn: ["A.I. Specialization Track", "Industry-Joint Capstone Project", "Global University Internships"],
  },
  {
    id: "dept-2",
    category: "engineering",
    nameKo: "반도체공학과",
    nameEn: "Semiconductor Engineering",
    descKo: "차세대 K-반도체 산업을 이끌 인재를 육성하고, 실제 웨이퍼 공정 및 설계 장비를 실습합니다.",
    descEn: "Training the future leaders of the global semiconductor field through actual cleanroom fabrication and silicon design labs.",
    featuresKo: ["FAB 클린룸 실습실 보유", "국내 굴지 반도체 기업 매칭", "장학금 100% 수혜 제도"],
    featuresEn: ["On-Campus FAB Cleanroom facility", "Direct Matching with Samsung/SK Hynix", "100% Full Scholarship Programs"],
  },
  {
    id: "dept-3",
    category: "humanities",
    nameKo: "국어국문창작학과",
    nameEn: "Korean Literature & Creative Writing",
    descKo: "한국 문학의 전통을 계승하고, 디지털 미디어 시대를 선도할 현대적 스토리텔링 전문가를 가르칩니다.",
    descEn: "Inheriting the rich history of Korean letters while guiding content creators for the digital storytelling age.",
    featuresKo: ["신춘문예 등단 장려 코스", "K-컨텐츠 시나리오 작가 워크숍", "출판 및 편집인 아카데미"],
    featuresEn: ["Creative Literary Debut Mentorship", "K-Content Screenwriting Labs", "Digital Publishing Masterclass"],
  },
  {
    id: "dept-4",
    category: "natural",
    nameKo: "바이오메디컬학과",
    nameEn: "Biomedical Science",
    descKo: "생명체의 기초 원리를 탐구하고 백신, 유전공학, 분자의학의 실증 연구를 수행합니다.",
    descEn: "Studying pure life sciences and executing translation studies in pharmaceutical synthesis, gene therapy, and public health.",
    featuresKo: ["첨단 생명 분석 장비 활용", "질병관리청 등 국책 연구소 인턴", "학/석사 연계 우수과정"],
    featuresEn: ["Advanced Biosensors and Micro-imaging", "KDCA Government Residency Placement", "Accelerated BS/MS Programs"],
  },
  {
    id: "dept-5",
    category: "arts",
    nameKo: "영화영상학과",
    nameEn: "Film & Cinematic Arts",
    descKo: "최첨단 카메라 기기와 전문 음향 스튜디오를 갖추어 글로벌 영화 시장의 주역을 배출해 냈습니다.",
    descEn: "Equipped with state-of-the-art camera systems and professional recording suites to produce award-winning visual directors.",
    featuresKo: ["충북 국제 영화제 정기 출품", "현업 감독 초빙 실무 지도", "개인 단편 영화 제작비 전액 지원"],
    featuresEn: ["Official Submissions to Local Film Festivals", "Active Director One-on-one Masterclasses", "Production Budget Sponsorship"],
  },
  {
    id: "dept-6",
    category: "medical",
    nameKo: "간호학과",
    nameEn: "Nursing Studies",
    descKo: "체계적인 임상 실습 프로그램과 최고의 국시 합격률을 지탱하는 간호 전문 인재를 육성합니다.",
    descEn: "Nurturing dedicated, technically superior medical helpers through standard clinical residencies and state national exam passing rates.",
    featuresKo: ["종합 시뮬레이션 센터 운영", "대학병원 중심 풍부한 실습 기회", "간호사 국가고시 합격 보장반"],
    featuresEn: ["Advanced Simulation Center Labs", "Abundant University Hospital Rotations", "100% License Examination Guarantee"],
  }
];

export const SEARCH_DATABASE: SearchItem[] = [
  { titleKo: "입학 전형", titleEn: "Admissions Process", categoryKo: "입학", categoryEn: "Admissions", url: "#admissions" },
  { titleKo: "학부 입학 절차", titleEn: "Undergraduate Enrollment", categoryKo: "입학", categoryEn: "Admissions", url: "#admissions-undergrad" },
  { titleKo: "대학원 모집 요강", titleEn: "Graduate Syllabus", categoryKo: "대학원", categoryEn: "Graduate", url: "#admissions-grad" },
  { titleKo: "장학금 제도 안내", titleEn: "Scholarship Benefits", categoryKo: "학사/장학", categoryEn: "Scholarships", url: "#scholarships" },
  { titleKo: "기숙사 신청 및 생활관 안내", titleEn: "Dormitory Application", categoryKo: "캠퍼스 라이프", categoryEn: "Campus Life", url: "#dormitory" },
  { titleKo: "컴퓨터공학과 학과 소개", titleEn: "Computer Science Dept Overview", categoryKo: "학과안내", categoryEn: "Departments", url: "#dept-1" },
  { titleKo: "반도체공학과 학과 소개", titleEn: "Semiconductor Engineering Details", categoryKo: "학과안내", categoryEn: "Departments", url: "#dept-2" },
  { titleKo: "간호학과 보건 교육 실습", titleEn: "Nursing Clinical Residencies", categoryKo: "학과안내", categoryEn: "Departments", url: "#dept-6" },
  { titleKo: "외국인 유학생 전형", titleEn: "International Admissions", categoryKo: "입학", categoryEn: "Admissions", url: "#admissions-inter" },
  { titleKo: "캠퍼스 버스 노선 및 요금", titleEn: "Shuttle Bus Schedule", categoryKo: "캠퍼스 라이프", categoryEn: "Campus Life", url: "#campus-shuttle" },
];

export const TRANSLATIONS = {
  ko: {
    portalTitle: "통합 대학 입학 포털",
    selectUniv: "대학 선택",
    backToHome: "메수 페이지로",
    searchPlaceholder: "어떤 정보를 찾으시나요? 학과, 장학금, 모집 요강 등...",
    popularSearchBtn: "인기 검색어",
    recentSearchTitle: "최근 검색어",
    notFoundedSearch: "검색 결과가 없습니다.",
    navAdmissions: "입학안내",
    navDepts: "학과안내",
    navCampusLife: "캠퍼스 라이프",
    navNews: "새소식",
    navCounsel: "입학상담",
    welcomeTitle: "에 오신 것을 환영합니다",
    welcomeSub: "창의적 사고와 끊임없는 도전으로 내일의 미래를 여는 인재를 찾습니다. 글로벌 배움의 마당에서 꿈을 현실로 실현시키세요.",
    tourBtn: "캠퍼스 투어",
    exploreBtn: "입학 정보 둘러보기",
    admissionTitle: "입학 전형 및 학부 과정",
    admissionsSub: "각 분야의 미래를 선도할 인재를 기다립니다. 원서 접수 일정과 요건을 확인해 보세요.",
    undergradTitle: "학부 과정",
    undergradDesc: "수시, 정시, 편입학 모드를 통한 국내 최고 수준의 전공 교과과정 제공.",
    gradTitle: "대학원 과정",
    gradDesc: "석사, 박사, 연구과정을 포함하는 고도화된 연구 및 실무 융합 학위.",
    interTitle: "외국인 전형",
    interDesc: "글로벌 리더 양성을 위한 맞춤 배려 교육과 다양한 언어 전공 전형.",
    scheduleEvent: "2025학년도 입학 설명회 안내",
    eventDate: "일시: 2025년 6월 12일 (목) 14:00",
    eventLocation: "장소: 대학 본부 대강당 및 YouTube 실시간 생중계",
    countDownTitle: "설명회 개최까지 남은 시간",
    days: "일",
    hours: "시간",
    minutes: "분",
    seconds: "초",
    counselFormTitle: "입학 상담 및 실시간 문의 신청",
    counselFormSub: "학과나 전형에 대한 궁금증을 적어 보내주시면, 입학 전문 조교 및 상담사가 직접 신속하고 상세하게 상담해 드립니다.",
    labelName: "이름 (실명)",
    labelContact: "연락처 번호",
    labelCategory: "상담 희망 분야",
    labelContent: "기록할 문의 내용 (상담 요청 상세)",
    agreePrivacyText: "개인정보 수집 및 상담 답변 전송 목적의 활용에 동의합니다.",
    submitBtn: "입학 상담 신청하기",
    formSuccessMsg: "입학 상담 신청이 성공적으로 접수되었습니다!",
    errName: "이름을 입력해 주세요. (2자 이상 한글/영문)",
    errContact: "올바른 연락처 형식을 지정하세요. (예: 010-1234-5678)",
    errContent: "상담 내용은 최소 10자 이상 500자 이하로 작성해 주세요.",
    errPrivacy: "개인정보 수집 이용 안내에 동의해야 상담이 가능합니다.",
    counselHistory: "내 최근 입학 상담 신청 이력",
    historyEmpty: "신청 이력이 없습니다. 질문이 있으시면 상담을 등록해 보세요.",
    deptFilterTitle: "학과 안내 탐색기",
    allCategory: "전체 학과",
    engineering: "공과/기술",
    humanities: "인문/스토리텔링",
    natural: "자연 과학",
    arts: "예술/디자인",
    medical: "보장 의학",
    cardStatsLabel: "학생 수",
    cardProfLabel: "전임 교수",
    cardEmployLabel: "실질 취업률",
    statsTitle: "주요 대학 지표",
    foundingYearLabel: "설립 연도",
    desktopMode: "데스크톱 뷰",
    mobileMode: "모바일 스마트폰 뷰",
    footerCopyright: "Copyright © All Rights Reserved.",
    navHome: "홈",
    majorColUnder: "학부 과정 지원",
    majorColGrad: "대학원 과정 지원",
    majorColInter: "글로벌/기타 전형",
    upcomingAdmissions: "다가오는 전형 세부",
    earlyDesc: "수시 모집 요강",
    regularDesc: "정시 모집 요강",
    transferDesc: "편입학 전형",
    specialgrad: "특수 대학원",
    phdgrad: "일반 대학원 석박사 과정",
    langSchool: "한국어 교실 코스",
    exchangeStudent: "교환 학생 우대 전형",
  },
  en: {
    portalTitle: "Unified University Admissions",
    selectUniv: "Select Campus",
    backToHome: "Main Directory",
    searchPlaceholder: "Search courses, scholarships, syllabus criteria...",
    popularSearchBtn: "Popular Tags",
    recentSearchTitle: "Recent Searches",
    notFoundedSearch: "No search matches found.",
    navAdmissions: "Admissions",
    navDepts: "Departments",
    navCampusLife: "Campus Life",
    navNews: "News",
    navCounsel: "Consultation",
    welcomeTitle: "Welcome to",
    welcomeSub: "Unlocking tomorrow's frontiers through creative thinking and challenging endeavors. Realize your premium global academic goals in our research campus.",
    tourBtn: "Campus Tour",
    exploreBtn: "Explore Admissions",
    admissionTitle: "Admissions Guide",
    admissionsSub: "Find your path to global success. Check the scheduled application deadlines and entry criteria below.",
    undergradTitle: "Undergraduate",
    undergradDesc: "Admission guidelines for Early Selection, Regular Evaluation, and College Transfers.",
    gradTitle: "Graduate Programs",
    gradDesc: "Master's, Doctoral, and specialized collaborative research degrees.",
    interTitle: "International",
    interDesc: "Diverse language support and pathways optimized for active global students.",
    scheduleEvent: "2025 Admissions Info Briefing",
    eventDate: "Time: June 12, 2025 (Thu) 14:00 KST",
    eventLocation: "Venue: University Main Auditorium & YouTube livestream",
    countDownTitle: "Countdown to Briefing Event",
    days: "Days",
    hours: "Hours",
    minutes: "Mins",
    seconds: "Secs",
    counselFormTitle: "Admissions consultation & Helpdesk",
    counselFormSub: "Submit your academic inquiries below. Our admissions advisors and graduate student guides will review and reply swiftly.",
    labelName: "Full Name",
    labelContact: "Contact Number",
    labelCategory: "Area of Interest",
    labelContent: "Inquiry Content Detail",
    agreePrivacyText: "I agree to the collection and processing of personal data for school counseling.",
    submitBtn: "Submit Consultation Request",
    formSuccessMsg: "Your admissions inquiry has been successfully registered!",
    errName: "Please enter your name. (At least 2 characters)",
    errContact: "Provide a valid contact format. (e.g. 010-1234-5678 or 10-20 digits)",
    errContent: "Content text must be between 10 and 500 characters long.",
    errPrivacy: "You must accept the privacy processing to submit inquiries.",
    counselHistory: "Your Consultation Inquiry History",
    historyEmpty: "No inquiries registered yet. Post your first consultation question above!",
    deptFilterTitle: "Academic Catalog Explorer",
    allCategory: "All Departments",
    engineering: "Engineering & Tech",
    humanities: "Humanities & Writing",
    natural: "Natural Sciences",
    arts: "Arts & Cinema",
    medical: "Medical & Nursing",
    cardStatsLabel: "Enrollment size",
    cardProfLabel: "Faculty strength",
    cardEmployLabel: "Employment Rate",
    statsTitle: "University Quick Facts",
    foundingYearLabel: "Established In",
    desktopMode: "Desktop View",
    mobileMode: "Mobile Device View",
    footerCopyright: "Copyright © All Rights Reserved.",
    navHome: "Home",
    majorColUnder: "Undergraduate Admission",
    majorColGrad: "Graduate Selection",
    majorColInter: "Global & Foreign Programs",
    upcomingAdmissions: "Admissions Calendar",
    earlyDesc: "Early Admissions",
    regularDesc: "Regular Decidsion",
    transferDesc: "Transfer Admissions",
    specialgrad: "Specialized Graduate Sch",
    phdgrad: "General Master / Ph.D.",
    langSchool: "Korean Language Course",
    exchangeStudent: "Exchange Affiliation",
  },
};
